title: "AI Blog"
description: "Exploring the world of AI, one learning at a time."
url: "https://s23deepak.github.io"
baseurl: ""
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap